"""Command Code provider profile for the local bridge."""
from providers import register_provider
from providers.base import OMIT_TEMPERATURE, ProviderProfile

commandcode = ProviderProfile(
    name="commandcode",
    aliases=("command-code", "commandcode-alpha", "cc"),
    display_name="Command Code",
    description="Command Code Go subscription via local OpenAI-compatible bridge (v0.2)",
    signup_url="https://commandcode.ai/",
    env_vars=("COMMANDCODE_API_KEY",),
    base_url="http://127.0.0.1:8788/v1",
    models_url="http://127.0.0.1:8788/v1/models",
    auth_type="api_key",
    fixed_temperature=OMIT_TEMPERATURE,
    default_max_tokens=32000,
    default_aux_model="deepseek/deepseek-v4-flash",
    fallback_models=(
        "claude-sonnet-5",
        "claude-sonnet-4-6",
        "claude-fable-5",
        "claude-opus-5",
        "claude-opus-4-8",
        "claude-opus-4-7",
        "claude-haiku-4-5-20251001",
        "gpt-5.6-sol",
        "gpt-5.6-terra",
        "gpt-5.6-luna",
        "gpt-5.5",
        "gpt-5.4",
        "gpt-5.3-codex",
        "gpt-5.4-mini",
        "moonshotai/Kimi-K3",
        "moonshotai/Kimi-K2.7-Code",
        "moonshotai/Kimi-K2.7-Code-Highspeed",
        "moonshotai/Kimi-K2.6",
        "moonshotai/Kimi-K2.5",
        "zai-org/GLM-5.2",
        "zai-org/GLM-5.2-Fast",
        "zai-org/GLM-5.1",
        "zai-org/GLM-5",
        "MiniMaxAI/MiniMax-M3",
        "MiniMaxAI/MiniMax-M2.7",
        "MiniMaxAI/MiniMax-M2.5",
        "deepseek/deepseek-v4-pro",
        "deepseek/deepseek-v4-flash",
        "Qwen/Qwen3.8-Max",
        "Qwen/Qwen3.7-Max",
        "Qwen/Qwen3.7-Plus",
        "Qwen/Qwen3.7-Flash",
        "Qwen/Qwen3.6-Max-Preview",
        "Qwen/Qwen3.6-Plus",
        "stepfun/Step-3.7-Flash",
        "stepfun/Step-3.5-Flash",
        "tencent/hy3-paid",
        "nvidia/nemotron-3-ultra-550b-a55b",
        "sakana/fugu-ultra",
        "google/gemini-3.6-flash",
        "google/gemini-3.5-flash",
        "google/gemini-3.5-flash-lite",
        "google/gemini-3.1-flash-lite",
        "xiaomi/mimo-v2.5-pro",
        "xiaomi/mimo-v2.5",
        "thinkingmachines/inkling",
        "thinkingmachines/inkling-small",
        "poolside/laguna-s-2.1-free",
        "meta/muse-spark-1.1",
        "meta/muse-spark-1.2",
        "meta/muse-spark-1.2-contributor",
        "xai/grok-4.5"
    ),
)

register_provider(commandcode)
